targets:
  $default:
    builders:
      bloc_use_case_generator:
        enabled: true

builders:
  bloc_use_case_generator:
    target: ":bloc_use_case_generator"
    import: "package:bloc_use_case_generator/builder.dart"
    builder_factories: ['generateBloc']
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
