name: bloc_use_case_generator
description: Generates event and states for flutter_bloc
version: 1.2.0
homepage: https://github.com/oguzhan2142/bloc_use_case_generator

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.24.2
