name: bloc_generator
description: Generates event and states for flutter_bloc
version: 1.0.0
homepage: https://github.com/oguzhan2142/bloc_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^4.6.0
  build: ^2.3.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  test: ^1.21.4
