name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  annotations:
    path: ../annotations/

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.2.0
  test: ^1.21.4
